version: '3.7'

services:
  portfolio-website:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - $PORT:$PORT
    volumes:
      - ./src:/portfolio-website/src
    env_file:
      - .env
    command: npm run dev
