version: '3.7'

services:
  portfolio-website:
    network_mode: host
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/portfolio-website/src
    command: npm run dev
