version: '3.7'

services:
  portfolio-website:
    image: ghcr.io/trinhxuantam/portfolio-website:latest
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - portfolio-network

networks:
  portfolio-network:
    name: portfolio-network
